# Generated by Django 4.2.7 on 2023-11-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img_productos', verbose_name='Imagen'),
        ),
    ]
